import {Injectable} from '@angular/core';
import {FaIconLibrary} from '@fortawesome/angular-fontawesome';

import {
  faArrowLeft,
  faArrowRightFromBracket,
  faBagShopping,
  faBars,
  faBell,
  faCalendar,
  faCalendarPlus, faChildren,
  faCircleQuestion, faClock,
  faClover, faEuroSign,
  faFlagCheckered,
  faFloppyDisk,
  faGears,
  faGem,
  faHouseUser,
  faInfoCircle,
  faListUl,
  faLocationPin,
  faMedal,
  faPencil,
  faPersonRunning,
  faPlus,
  faPlusCircle,
  faRankingStar,
  faRoad,
  faRulerHorizontal,
  faShower,
  faSignInAlt,
  faSliders,
  faStar,
  faStarHalfStroke,
  faToilet, faTrash,
  faTrophy,
  faTShirt,
  faUser,
  faUserGroup,
  faUserPlus,
  faUsersBetweenLines,
  faMagnifyingGlass,
  faUpload, faUserMinus, faChild,
} from '@fortawesome/free-solid-svg-icons';

import {faHeart as faHeartRegular} from '@fortawesome/free-regular-svg-icons';

@Injectable({providedIn: 'root'})
export class IconService {
  constructor(private library: FaIconLibrary) {
    this.library.addIcons(
      faTrophy,
      faPersonRunning,
      faFlagCheckered,
      faInfoCircle,
      faRoad,
      faToilet,
      faShower,
      faMedal,
      faBagShopping,
      faTShirt,
      faUsersBetweenLines,
      faListUl,
      faStar,
      faClover,
      faBell,
      faArrowRightFromBracket,
      faCircleQuestion,
      faHouseUser,
      faRankingStar,
      faUserGroup,
      faGem,
      faSliders,
      faUser,
      faBars,
      faHeartRegular,
      faFloppyDisk,
      faArrowLeft,
      faSignInAlt,
      faUserPlus,
      faGears,
      faCalendarPlus,
      faStarHalfStroke,
      faCalendar,
      faLocationPin,
      faPencil,
      faPlusCircle,
      faPlus,
      faChildren,
      faClock,
      faRulerHorizontal,
      faEuroSign,
      faTrash,
      faMagnifyingGlass,
      faUpload,
      faUserMinus,
      faChild
    );
  }
}
